### ISSUE TITLE
fwTool compillation issues

### ISSUE THREAD

**Issue by piratesephiroth** [WinterMute/nintendo-ds-tools#1]
There's this error with the arm9 elf. Do we somethig special to build it? An additional lib?

I thought it was because of the different libnds  I was using but I restored the original one from devkitpro and it's still happening.

![screenshot](http://i.imgur.com/pvC19MN.png)

**Comment by idgrepthat** [comment]
https://github.com/search?q=nand_getsize&type=Code&utf8=%E2%9C%93

Update to latest libnds, not the release 45 one.
