### ISSUE TITLE
fwtool compile issue

### ISSUE THREAD

**Issue by al3x10m** [WinterMute/nintendo-ds-tools#2]
https://github.com/WinterMute/nintendo-ds-tools/blob/master/firmware/nds/fwTool/arm9/source/main.cpp#L85

shouldn't be "if (isDSiMode()) {" ?

**Comment by WinterMute** [comment]
This was fixed & moved to https://github.com/WinterMute/fwTool

I'm going to delete this repo at some point when I figure out what I want to do with the other stuff.

**Comment by al3x10m** [comment]
oh...wasn't aware. Thanks!
